# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd0f7283360c10b7484d8f1d6dfdcfb0190cb55f738fcc5c407ceed10d8ee5cdcd66ad0d201e3c6085d9c1faa5ef57e89ae504a8aaa80ca25c35f3a09d213001

test:
  secret_key_base: 3da808fbf7458047227d42dfbaad9dcc9dc1448a65e0d253f8dcd89e6e161018dff9f76bfd91f10ff769d939f8aa7eb80cdbec81c287671d53fdf36ee9d1481a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
